name: Build Package (Julia 1.8.5)
on:
  push:
    branches:
      - abf/transancestry
    tags: '*'
  pull_request:
defaults:
  run:
    shell: bash
jobs:
  build-julia-1-8-5:
    name: build-julia-1-8-5
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.8.5'
        os:
          - ubuntu-latest
          #- macOS-latest
          #- windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - run: |
          cd ..
      - run: julia --project -e 'using Pkg; Pkg.add("PackageCompiler")'
      - run: julia --project -e 'create_app("PolygenicRiskScores.jl", "PRS.jl-compiled", force=true)'
      - uses: actions/upload-artifact@v3
        with:
          name: PRS.jl-compiled
          path: PRS.jl-compiled/
